### ISSUE TITLE
คำถามเกี่ยวกับ assignment

### ISSUE THREAD

**Issue by swsd2544** [up1/assignment-java-boot-camp#11]
สวัสดีครับ ผมยังไม่เคยเริ่มงานในด้านสายนี้แบบจริงจังเลยยังตามไม่ค่อยทันเท่าไหร่ พอจะอธิบายให้ได้มั้ยครับว่า flow ที่หมายถึงคือเป็นแบบไหนครับ (อยากให้มีตัวอย่างด้วยครับ) แล้วก็ตัว api ที่ต้องทำนี่คือต้องใช้จริงได้เลยมั้ยครับ

**Comment by up1** [comment]
เป็น workflow หรือการเข้าใช้งานระบบจากมุมมองของผู้ใช้งานนะครับ

ตัวอย่างเช่น นายเอ เข้ามาค้นหา beer จะเจอข้อมูล beer จำนวน 3 ตัว คือ สิงห์ ช้าง และ ลีโอ (ซึ่งแต่ละตัวจะมีรายละเอียดเพิ่มเติม เราเขียนอธิบาย beer แต่ละตัวได้ )

จากนั้นนาเอ เข้าดูรายละเอียดของ beer สิงห์ จะเห็นข้อมูลอะไรบ้าง ...

ไปเรื่อย ๆ แบบนี้ จนจบหน้าสุดท้าย

เป็นระบุความต้องการนะครับ

**Comment by up1** [comment]
ตัว api ที่สร้าง สามารถใช้งานได้ตามที่เราออกแบบเลยครับ ว่าต้องมี api อะไรบ้าง มีรูปแบบของ request และ response อย่างไร

จากนั้นจึงพัฒนาด้วย spring boot

**Comment by up1** [comment]
จากตัวอย่าง flow ที่ผมเขียนสั้น ๆ ก็จะมี api 2 ตัวคือ การค้นหา และ การดูรายละเอียด

**Comment by swsd2544** [comment]
ขอบคุณครับ
