### ISSUE TITLE
ปัญหาการใช้ throw exception 

### ISSUE THREAD

**Issue by petchy** [up1/assignment-java-boot-camp#17]
<img width="564" alt="2022-02-20_10-56-51" src="https://user-images.githubusercontent.com/3236449/154827905-92f22200-3189-4f90-ac05-92c5adf0e2c2.png">

ตอนนี้ผมมีปัญหาว่าต้องเขียน if ดักไว้สำหรับไม่ให้เคส error เข้ามาทำ อยากทราบว่าต้องแก้อย่างไรครับ

code ใน repository ครับ
https://github.com/petchy/assignment-java-boot-camp

**Comment by up1** [comment]
ทำใน RestControllerAdvice แล้วไม่ใช่หรอครับ ?

**Comment by petchy** [comment]
<img width="933" alt="2022-02-20_11-36-25" src="https://user-images.githubusercontent.com/3236449/154828617-b66365de-36b5-4d26-9acc-0c2086ec936d.png">

ทำแล้วครับ แต่ถ้าผมไม่ if ไว้มันจะได้แบบนี้ครับ

**Comment by petchy** [comment]
![image](https://user-images.githubusercontent.com/3236449/154830091-22f3d1af-7a3d-44db-b2dc-59fb7a3b76a2.png)
อ่อได้แล้วครับ ต้องไป set null ใน controllerAdvice ถ้าไม่set มันจะเอาค่าเก่ามาแสดงด้วยครับ

**Comment by up1** [comment]
การแก้ไขที่ถูกต้องคือ เอา `@Component` ออกไปครับ เพราะว่า มันคือ singleton นะครับ อันตรายมาก ๆ

```
@Component
public class ProductResponse{

	private ArrayList<Product> data;
	private String message;
```

**Comment by petchy** [comment]
ผมแก้ตามที่อาจารย์บอกแล้ว ขอบคุณครับ
